const ptBR: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Sequências de título',
    'STR_TITLE_SEQUENCE': 'Sequência de Títulos:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Criar',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Cria uma nova sequência de título a partir de um rascunho',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duplicar',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Cria uma nova sequência de título baseada na atual',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Exclui a sequência de título atual',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Renomear',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Renomeia a sequência de título atual',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Adicionar',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Remover',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Carregar',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Editar',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Ir para',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Insere um novo comando',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Edita o comando selecionado',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Exclui o comando selecionado',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Pula para o comando selecionado na sequência de título',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Move o comando selecionado para cima',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Move o comando selecionado para baixo',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Reinicia sequência de título',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Para sequência de título',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Executa sequência de título',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Pula para o próximo comando de espera',
    'STR_YES': 'Sim',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Cancelar',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Selecionar Sprite',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Comando:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Editor de Comando',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Carregar Jogo Salvo',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Salvar para carregar:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Carregar Cenário',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Cenário para carregar:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Localização',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Girar',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Ampliar',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Velocidade',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Seguir Sprite',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Aguardar',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Coordenadas:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Rotações anti-horárias:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Nível de ampliação:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Velocidade:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Milissegundos de espera:',
    'STR_TITLE_EDITOR_RESTART': 'Reiniciar',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Conseguir',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Velocidade Normal',
    'STR_SPEED_QUICK': 'Velocidade Rápida',
    'STR_SPEED_FAST': 'Velocidade Muito Rápida',
    'STR_SPEED_TURBO': 'Velocidade Turbo',
    'STR_SPEED_HYPER': 'Hiper Velocidade',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Jogo salvo não selecionado',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Nenhum cenário selecionado',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Insira um nome para a sequência de título',
};