const eoZZ: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Titolosekvencoj',
    'STR_TITLE_SEQUENCE': 'Titolosekvenco:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Krei',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Krei novan titolosekvencon de nulo',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duobligi',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Krei novan titolosekvencon surbaze de la nuna',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Foriga klavo',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Forigi la nunan titolosekvencon',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Renomi',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Renomi la nunan titolosekvencon',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Aldoni',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Forigi',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Ŝargi',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Enmeta klavo',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Redakti',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Preterpasi al',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Enmeti novan komandon',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Redakti la elektitan komandon',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Forigi la elektitan komandon',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Preterpasi al la elektita komando en la titolosekvenco',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Movi la elektitan komandon malsupren',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Movi la elektitan komandon supren',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Rekomenci titolosekvencon',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Halti ludi titolosekvencon',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Komenci ludi titolosekvencon',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Preterpasi al sekva haltokomando',
    'STR_YES': 'Jes',
    'STR_OK': 'Daŭrigi',
    'STR_CANCEL': 'Nuligi',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Elekti Rastrumeton',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Komando:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Komandoredaktilo',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Ŝargi Konservaĵon',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Konservi por ŝargi:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Ŝargi Scenaron',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Scenaro por ŝargi:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Loko',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Turni',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Zomi',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Rapideco',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Sekvi Rastrumeton',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Atendi',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Koordinatoj:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Maldekstrumaj turnoj:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Zomonivelo:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Rapideco:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Atendi tiom da milisekundoj:',
    'STR_TITLE_EDITOR_RESTART': 'Rekomenci',
    'STR_TITLE_EDITOR_END': 'Fina klavo',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Atingi',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Elektoklavo',
    'STR_SPEED_NORMAL': 'Normala Rapideco',
    'STR_SPEED_QUICK': 'Rapideta Rapideco',
    'STR_SPEED_FAST': 'Rapida Rapideco',
    'STR_SPEED_TURBO': 'Rapidega Rapideco',
    'STR_SPEED_HYPER': 'Ekstrema Rapideco',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Neniu konservaĵo elektita',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Neniu scenaro elektita',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Entajpu nomon de la titolosekvenco',
};