const fiFI: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Valikkotaustat',
    'STR_TITLE_SEQUENCE': 'Päävalikon tausta:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Luo',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Luo uusi valikkotausta tyhjästä',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Kopioi',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Luo uusi valikkotausta nykyisestä',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Poista nykyinen valikkotausta',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Uudelleennimeä',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Nimeä nykyinen valikkotausta uudelleen',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Lisää',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Poista',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Lataa',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Muokkaa',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Siirry',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Lisää uusi komento',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Muokkaa uusi komento',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Poista valittu komento',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Siirry valittuun komentoon valikkotaustassa',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Siirrä valittu komento alas',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Siirrä valittu komento ylös',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Aloita valikkotausta alusta',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Lopeta valikkotaustan toisto',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Toista valikkotausta',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Siirry seuraavaan odotuskomentoon',
    'STR_YES': 'Kyllä',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Peruuta',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Valitse sprite',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Komento:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Komentojenmuokkain',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Lataa tallennus',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Tallenna lataakseen:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Lataa skenaario',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Ladattava skenaario:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Sijainti',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Käännä',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Zoomaa',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Nopeus',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Seuraa spriteä',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Odota',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Koordinaatit:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Vastapäivään käännökset:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Suurennus:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Nopeus:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Sekuntia odottaa:',
    'STR_TITLE_EDITOR_RESTART': 'Uudelleen käynnistä',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Hanki',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Normaalinopeus',
    'STR_SPEED_QUICK': 'Pikanopeus',
    'STR_SPEED_FAST': 'Vauhtinopeus',
    'STR_SPEED_TURBO': 'Turbonopeus',
    'STR_SPEED_HYPER': 'Hypernopeus',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Tallennusta ei valittuna',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Ei valittua skenaariota',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Anna nimi valikkotaustalle',
};