const plPL: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Tytułowe sekwencje',
    'STR_TITLE_SEQUENCE': 'Sekwencja tytułowa:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Stwórz',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Utwórz nową sekwencję tytułów od podstaw',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duplikuj',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Stwórz nową sekwencję tytułową, na podstawie obecnej',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Usuń obecną sekwencję tytułową',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Zmień nazwę',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Zmień nazwę obecnej sekwencji tytułowej',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Dodaj',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Usuń',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Załaduj',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Edytuj',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Skocz do',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Wstaw nową komendę',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Edytuj wybraną komendę',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Usuń wybraną komendę',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Skocz do wybranej komendy w sekwencji tytułowej',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Przesuń wybraną komendę w dół',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Przesuń wybraną komendę w górę',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Zrestartuj sekwencję tytułową',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Przestań odtwarzać sekwencję tytułową',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Zacznij odtwarzać sekwencję tytułową',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Skocz do następnej komendy czekania',
    'STR_YES': 'Tak',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Anuluj',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Wybierz sprite’a',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Komenda:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Edytor komand',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Wczytaj zapisany plik',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Zapis do załadowania:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Załaduj scenariusz',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Scenariusz do załadowania:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Lokalizacja',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Obróć',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Powiększ',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Prędkość',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Śledź sprite’a',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Czekaj',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Pozycja:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Odwrotnie do wskazówek zegara:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Poziom przybliżenia:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Prędkość:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Pozostało milisekund:',
    'STR_TITLE_EDITOR_RESTART': 'Restart',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Pobierz',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Wybierz',
    'STR_SPEED_NORMAL': 'Normalnie',
    'STR_SPEED_QUICK': 'Szybko',
    'STR_SPEED_FAST': 'Bardzo szybko',
    'STR_SPEED_TURBO': 'Super szybko',
    'STR_SPEED_HYPER': 'Hiper szybko',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Nie wybrano zapisu',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Nie wybrano scenariusza',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Wpisz nazwę tytułowej sekwencji',
};