const huHU: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Főcímek',
    'STR_TITLE_SEQUENCE': 'Főcím:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Létrehozás',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Egy teljesen új főcím létrehozása',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Másolatkészítés',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Új főcím létrehozása a jelenlegi alapján',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'A jelenlegi főcím törlése',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Átnevezés',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'A jelenlegi főcím átnevezése',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Hozzáadás',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Törlés',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Betöltés',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Szerkesztés',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Ugrás',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Új parancs beszúrása',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'A kiválasztott parancs szerkesztése',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'A kiválasztott parancs törlése',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'A főcím a kiválasztott parancshoz ugrik',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'A kiválasztott parancs feljebb mozgatása',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'A kiválasztott parancs lejjebb mozgatása',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'A főcím újraindítása',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'A főcím leállítása',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'A főcím lejátszása',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Ugrás a következő várakozás parancsra',
    'STR_YES': 'Igen',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Mégse',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Sprite kiválasztása',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Parancs:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Parancsszerkesztő',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Mentés betöltése',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Betölteni kívánt mentés:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Pálya betöltése',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Betöltendő pálya:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Hely',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Forgatás',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Nagyítás',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Sebesség',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Követés ',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Várakozás',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Koordinátái:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Órajárással ellentétes forgások:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Nagyítási szint:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Sebesség:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Várakozás (ezredmásodperc):',
    'STR_TITLE_EDITOR_RESTART': 'Újraindítás',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Jelenlegi',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Kiválasztás',
    'STR_SPEED_NORMAL': 'Normál sebesség',
    'STR_SPEED_QUICK': 'Gyors sebesség',
    'STR_SPEED_FAST': 'Extra gyors sebesség',
    'STR_SPEED_TURBO': 'Turbó sebesség',
    'STR_SPEED_HYPER': 'Hipersebesség',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Nincs kiválasztva mentés',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Nincs pálya kiválasztva',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Írj be egy nevet a főcím számára',
};