const trTR: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Başlık dizileri',
    'STR_TITLE_SEQUENCE': 'Kullanılan başlık dizisi:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Yeni',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Sıfırdan yeni bir başlık dizisi oluşturunuz',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Kopyala',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Yeni başlık dizisi üretiniz',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Şu an seçili olan başlık dizisini siliniz',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Yeni isim',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Şu an seçili olan başlık dizisinin ismini değiştiriniz',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Ekle',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Sil',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Yükle',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Düzenle',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Atla',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Yeni bir komut ekleyeiniz',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Seçilen komutu düzenleyiniz',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Seçilen komutu siliniz',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Seçili komuta atlayınız',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Seçilen komutu aşağı aktarınız',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Seçilen komutu yukarı aktarınız',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Başlık dizisini yeniden başlatınız',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Başlık dizisini durdurunuz',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Başlık dizisini başlatınız',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Bir sonraki bekleme komutuna geçiniz',
    'STR_YES': 'Evet',
    'STR_OK': 'Tamam',
    'STR_CANCEL': 'Iptal',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Alet/Kişi seçiniz',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Komut:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Komut listesi',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Kayıdlı oyun yükle',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Yüklenecek oyun:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Senaryo yükle',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Seçilen senaryo:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Bir yer',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Çevir',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Yakınlaştır',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Hız',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Takip',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Bekle',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Koordinatlar:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Saat yönünün tersine çevirme sayısı:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Yakınlık seviyesi:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Hız:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Beklenecek milisaniye:',
    'STR_TITLE_EDITOR_RESTART': 'Yeniden başlat',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Aktar',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Normal hız',
    'STR_SPEED_QUICK': 'Hızlı',
    'STR_SPEED_FAST': 'Çok hızlı',
    'STR_SPEED_TURBO': 'Turbo hızı',
    'STR_SPEED_HYPER': 'Devasal hız',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Kayıdlı oyun seçilmedi',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Senaryo seçilmedi',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Bu başlık dizisi için yeni isim giriniz',
};