const frFR: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Séquences de titre',
    'STR_TITLE_SEQUENCE': 'Séquence titre :',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Créer',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Créer une nouvelle séquence titre de zéro',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Dupliquer',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Créer une nouvelle séquence titre d’après l’actuelle',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Supprimer',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Supprimer l’actuelle séquence titre',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Renommer',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Renommer l’actuelle séquence titre',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Ajouter',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Retirer',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Charger',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insertion',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Editer',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Passer à',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Insérer une nouvelle commande',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Editer la commande sélectionnée',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Supprimer la commande sélectionée',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Passer à la commande sélectionnée dans la séquence titre',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Déplacer la commande sélectionnée vers le bas',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Déplacer la commande sélectionnée vers le haut',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Redémarrer séquence titre',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Arrêter séquence titre',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Démarrer séquence titre',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Passer à la commande suivante',
    'STR_YES': 'Oui',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Annuler',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Sélectionner image-objet',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Commande :',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Editeur de commande',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Charger sauvegarde',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Sauvegarde à charger :',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Charger scénario',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Scénario à charger :',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Emplacement',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Tourner',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Zoomer',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Vitesse',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Suivre image-objet',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Attendre',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Coordonnées :',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Rotations antihoraires :',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Niveau de zoom :',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Vitesse :',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Temps en millisecondes :',
    'STR_TITLE_EDITOR_RESTART': 'Redémarrer',
    'STR_TITLE_EDITOR_END': 'Fin',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Obtenir',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Sélectionner',
    'STR_SPEED_NORMAL': 'Vitesse normale',
    'STR_SPEED_QUICK': 'Vitesse rapide',
    'STR_SPEED_FAST': 'Vitesse très rapide',
    'STR_SPEED_TURBO': 'Vitesse turbo',
    'STR_SPEED_HYPER': 'Vitesse hyper',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Aucune sauvegarde sélectionnée',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Aucune scénario sélectionné',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Saisissez un nom pour la séquence titre',
};