const jaJP: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'タイトル順序',
    'STR_TITLE_SEQUENCE': 'タイトル順序:',
    'STR_TITLE_EDITOR_ACTION_CREATE': '新規',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': '新しいタイトル順序を造るために',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': '複写',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Create a new title sequence based on the current one',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Delete the current title sequence',
    'STR_TITLE_EDITOR_ACTION_RENAME': '名前を変更',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Rename the current title sequence',
    'STR_TITLE_EDITOR_ACTION_ADD': '追加',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': '削除',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'ロード',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': '編集',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'スキップ',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Insert a new command',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Edit the selected command',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Delete the selected command',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Skip to the selected command in the title sequence',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Move the selected command down',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Move the selected command up',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Restart title sequence',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Stop playing title sequence',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Start playing title sequence',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Skip to next wait command',
    'STR_YES': 'はい',
    'STR_OK': 'OK',
    'STR_CANCEL': 'キャンセル',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'スプライトを選ぶ',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Command:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Command Editor',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'セーブのロード',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Save to load:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'シナリオのロード',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'シナリオを選ぶ:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': '場所',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': '回転',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'ズーム',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'スピード',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'スプライトのフォロー',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': '待機',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': '場所:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Anticlockwise rotations:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Zoom level:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'スピード:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Milliseconds to wait:',
    'STR_TITLE_EDITOR_RESTART': '再起動',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'ゲット',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': '通常スピード',
    'STR_SPEED_QUICK': 'クイックスピード',
    'STR_SPEED_FAST': '高速スピード',
    'STR_SPEED_TURBO': 'ターボスピード',
    'STR_SPEED_HYPER': 'ハイパースピード',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'No save selected',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'シナリオ選択なし',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Enter a name for the title sequence',
};