const caES: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Seqüències del menú principal',
    'STR_TITLE_SEQUENCE': 'Seqüència del menú principal:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Crea',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Crea una seqüència del títol des de zero.',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duplica',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Crea una nova seqüència per al menú principal basada en l’actual.',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Esborra',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Esborra la seqüència del menú principal actual.',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Canvia el nom',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Canvia el nom de la seqüència actual.',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Afegeix',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Treu',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Carrega',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Inserta',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Edita',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Salta a',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Afegeix una nova ordre.',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Edita l’ordre seleccionada.',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Esborra l’ordre seleccionada.',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Salta a l’ordre seleccionada de la seqüència.',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Mou l’ordre seleccionada cap avall.',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Mou l’ordre seleccionada cap amunt.',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Reinicia la seqüència.',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Para la seqüència del menú principal.',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Inicia la seqüència del menú principal.',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Avança a la pròxima ordre d’espera.',
    'STR_YES': 'Sí',
    'STR_OK': 'D’acord',
    'STR_CANCEL': 'Cancel·la',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Selecciona sprite',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Ordre:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Editor d’ordres',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Carrega una partida',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Partida que s’ha de carregar:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Carrega un escenari',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Escenari a carregar:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Posició',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Gira',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Enfoca',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Velocitat',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Segueix sprite',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Espera',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Coordenades:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Rotacions antihoràries:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Nivell de zoom:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Velocitat:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Mil·lisegons que cal esperar:',
    'STR_TITLE_EDITOR_RESTART': 'Torna a començar',
    'STR_TITLE_EDITOR_END': 'Final',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Obté',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Selecciona',
    'STR_SPEED_NORMAL': 'Velocitat normal',
    'STR_SPEED_QUICK': 'Velocitat accelerada',
    'STR_SPEED_FAST': 'Velocitat ràpida',
    'STR_SPEED_TURBO': 'Velocitat turbo',
    'STR_SPEED_HYPER': 'Hipervelocitat',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'No s’ha escollit cap desada',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'No s’ha seleccionat cap escenari',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Escriviu un nom per a la seqüència',
};