const daDK: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Titelsekvens',
    'STR_TITLE_SEQUENCE': 'Titel sekvens:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Opret',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Opret en ny titel sekvens fra bunden af',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Dupliker',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Opret en ny titelsekvens baseret på den nuværende',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Slet nuværende titelsekvens',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Omdøb',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Omdøb nuværende titelsekvens',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Tilføj',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Fjern',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Hent',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Rediger',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Skip til',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Indsæt en ny kommando',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Rediger valgte kommando',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Slet valgte kommando',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'spring til den valgte kommando i titelsekvensen',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Flyt valgte kommando ned',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Flyt valgte kommando op',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Genstart af titelsekvens',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Stop afspilning af titelsekvens',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Start afspilning af titelsekvens',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Skip til næste ventekommando',
    'STR_YES': 'Ja',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Afbryd',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Vælg Sprite',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Kommando:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Kommando redigering',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Hent Gemt',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Gemte der skal hentes:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Hent Scenarie',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Scenarie der skal hentes:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Lokation',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Roter',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Zoom',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Hastighed',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Følg Sprite',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Vent',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Koordinater:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Mod uret rotation:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Zoom niveau:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Hastighed:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Millisekunder der skal ventes:',
    'STR_TITLE_EDITOR_RESTART': 'Genstart',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Hent',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Normal hastighed',
    'STR_SPEED_QUICK': 'Kvik hastighed',
    'STR_SPEED_FAST': 'Hurtig hastighed',
    'STR_SPEED_TURBO': 'Turbo hastighed',
    'STR_SPEED_HYPER': 'Hyper hastighed',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Ingen gemninger valgt',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Ingen scenarie valgt',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Angiv et navn til titelsekvensen',
};