const nlNL: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Titelpresentaties',
    'STR_TITLE_SEQUENCE': 'Titelpresentatie:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Aanmaken',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Begint een nieuwe, lege titelpresentatie',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Kopiëren',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Een nieuwe titelpresentatie aanmaken die is gebaseerd op de huidige',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Huidige titelpresentatie verwijderen',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Hernoemen',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Huidige titelpresentatie hernoemen',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Toevoegen',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Verwijderen',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Laad',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Bewerken',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Spring naar',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Nieuw commando invoegen',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Geselecteerd commando bewerken',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Geselecteerd commando verwijderen',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Naar geselecteerd commando titelpresentatie springen',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Geselecteerd commando naar beneden verplaatsen',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Geselecteerd commando naar boven verplaatsen',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Titelpresentatie herstarten',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Stopt het afspelen van de titelpresentatie',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Start het afspelen van de titelpresentatie',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Ga naar volgend Wacht-commando',
    'STR_YES': 'Ja',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Annuleren',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Sprite selecteren',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Commando:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Commandobewerker',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Opgeslagen park laden',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Te laden opgeslagen spel:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Scenario laden',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Te laden scenario:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Locatie',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Draai',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Zoom',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Snelheid',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Sprite volgen',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Wacht',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Coördinaten:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Aant. draaiingen tegen de klok:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Zoomniveau:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Snelheid:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Te wachten milliseconden:',
    'STR_TITLE_EDITOR_RESTART': 'Herstarten',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Ophalen',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Selecteren',
    'STR_SPEED_NORMAL': 'Normaal',
    'STR_SPEED_QUICK': 'Vlot',
    'STR_SPEED_FAST': 'Hard',
    'STR_SPEED_TURBO': 'Turbo',
    'STR_SPEED_HYPER': 'Nitro',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Geen opgeslagen spel geselecteerd',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Geen scenario geselecteerd',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Voer een naam in voor de titelpresentatie',
};