const csCZ: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Herní sekvence',
    'STR_TITLE_SEQUENCE': 'Úvodní herní sekvence:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Vytvořit',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Vytvořit novou herní sekvenci',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duplikovat',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Vytvořit stejnou novou herní sekvenci',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Odebrat herní sekvenci',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Přejmenovat',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Přejmenovat herní sekvenci',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Přidat',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Odebrat',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Načíst',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Upravit',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Přeskočit na',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Vložit nový příkaz',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Upravit vybraný příkaz',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Odebrat vybraný příkaz',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Přeskočit na následující příkaz v sekvenci',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Přesunout příkaz níže',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Přesunout příkaz výše',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Restartovat herní sekvenci',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Zastavit herní sekvenci',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Spustit herní sekvenci',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Přeskočit na následující příkaz „Čekat“',
    'STR_YES': 'Ano',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Zrušit',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Zvolit sprite',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Příkaz:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Editor příkazů',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Načíst uloženou hru',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Uložená hra k načtení:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Načíst scénář',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Scénář k načtení:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Umístění',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Otočit',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Přiblížit',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Rychlost',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Následovat sprite',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Čekat',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Souřadnice:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Počet otočení proti směru hod.ruč.:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Úroveň přiblížení:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Rychlost:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Délka čekání (v milisekundách):',
    'STR_TITLE_EDITOR_RESTART': 'Restart',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Získat',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Normální rychlost',
    'STR_SPEED_QUICK': 'Vyšší rychlost',
    'STR_SPEED_FAST': 'Vysoká rychlost',
    'STR_SPEED_TURBO': 'Turbo rychlost',
    'STR_SPEED_HYPER': 'Hyper rychlost',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Nevybrána žádná uložená hra',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Zvolte scénář',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Zadejte název herní sekvence',
};