const svSE: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Titelsekvens',
    'STR_TITLE_SEQUENCE': 'Titelsekvens:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Skapa',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Skapa ny titelsekvens från början',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Kopiera',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Skapa en ny titelsekvens baserad på den nuvarande',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Ta bort nuvarande titelsekvens',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Byt namn',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Byt namn på nuvarande titelsekvens',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Lägg till',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Ta bort',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Ladda',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Redigera',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Hoppa till',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Skriv in nytt kommando',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Redigera det valda kommandot',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Ta bort det valda kommandot',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Hoppa till det valda kommandot i titelsekvensen',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Flytta det valda kommandot nedåt',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Flytta det valda kommandot uppåt',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Börja om titelsekvensen',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Sluta spela titelsekvensen',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Börja spela titelsekvensen',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Skippa till nästa vänta-kommando',
    'STR_YES': 'Ja',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Avbryt',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Välj objekt',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Kommando:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Kommandoredigerare',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Ladda sparfil',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Sparfil att ladda:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Ladda scenario',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Scenario att ladda:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Plats',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Rotera',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Zooma',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Hastighet',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Följ objekt',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Vänta',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Koordinater:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Moturs rotation:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Zoomnivå:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Hastighet:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Millisekunder att vänta:',
    'STR_TITLE_EDITOR_RESTART': 'Börja om',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Få',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Normal hastighet',
    'STR_SPEED_QUICK': 'Kvick hastighet',
    'STR_SPEED_FAST': 'Snabb hastighet',
    'STR_SPEED_TURBO': 'Turbohastighet',
    'STR_SPEED_HYPER': 'Hyperhastighet',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Ingen sparfil vald',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Inget scenario valt',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Skriv in ett namn för titelsekvensen',
};