const arEG: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Title Sequences',
    'STR_TITLE_SEQUENCE': 'Title Sequence:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'أنشئ',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Create a new title sequence from scratch',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duplicate',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Create a new title sequence based on the current one',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Delete the current title sequence',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'إعادة تسمية',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Rename the current title sequence',
    'STR_TITLE_EDITOR_ACTION_ADD': 'إضافة',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'مسح',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'تحميل',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'تعديل',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'تخطي لـ',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Insert a new command',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Edit the selected command',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Delete the selected command',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Skip to the selected command in the title sequence',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Move the selected command down',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Move the selected command up',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Restart title sequence',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Stop playing title sequence',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Start playing title sequence',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Skip to next wait command',
    'STR_YES': 'نعم',
    'STR_OK': 'حسناً',
    'STR_CANCEL': 'إلغاء',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'تحديد النقطة',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Command:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Command Editor',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'تحميل الحفظ',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Save to load:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'تحميل المشهد',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'المشهد للتحميل:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'الموقع',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'تدوير',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'تقريب',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'سرعة',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'متابعة النقطة',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'إنتظر',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'الإحداثيات:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Anticlockwise rotations:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Zoom level:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'السرعة:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Milliseconds to wait:',
    'STR_TITLE_EDITOR_RESTART': 'إعادة تشغيل',
    'STR_TITLE_EDITOR_END': 'End',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'أحصل',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'السرعة العادية',
    'STR_SPEED_QUICK': 'Quick Speed',
    'STR_SPEED_FAST': 'Fast Speed',
    'STR_SPEED_TURBO': 'Turbo Speed',
    'STR_SPEED_HYPER': 'Hyper Speed',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'No save selected',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'لا مشهد محدد',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Enter a name for the title sequence',
};