const esES: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Secuencias del Menú Principal',
    'STR_TITLE_SEQUENCE': 'Sec. Menú Principal:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Crear',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Crear una secuencia desde cero.',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duplicar',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Crear una secuencia de la pantalla de inicio basada en la actual',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Delete',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Borrar la secuencia de la pantalla de inicio actual',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Renombrar',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Renombrar la secuencia de la pantalla de inicio actual',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Añadir',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Quitar',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Cargar',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Insert',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Editar',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Cambiar a',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Insertar un nuevo comando',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Editar comando seleccionado',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Eliminar comando seleccionado',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Ir al comando seleccionado en la ventana de Secuencias de la pantalla de inicio',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Mover comando seleccionado arriba',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Mover comando seleccionado abajo',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Reiniciar secuencia de la pantalla de inicio',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Detener la secuencia de la pantalla de inicio',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Iniciar la secuencia de la pantalla de inicio',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Ir al siguiente comando de espera',
    'STR_YES': 'Sí',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Cancelar',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Elegir figura',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Comando:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Añadir comando',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Cargar partida',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Partida a cargar:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Cargar escenario',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Escenario a cargar:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Localización',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Rotar',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Enfocar',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Velocidad',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Seguir figura',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Esperar',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Coordenadas:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Rotaciones en contra del reloj:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Nivel de enfoque',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Velocidad:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Tiempo en milisegundos:',
    'STR_TITLE_EDITOR_RESTART': 'Reiniciar',
    'STR_TITLE_EDITOR_END': 'Fin',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Obtener',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Velocidad normal',
    'STR_SPEED_QUICK': 'Velocidad ligera',
    'STR_SPEED_FAST': 'Velocidad rápida',
    'STR_SPEED_TURBO': 'Velocidad turbo',
    'STR_SPEED_HYPER': 'Hiper velocidad',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Partida no seleccionada',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'No se eligió escenario',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Escribe un nombre para la secuencia',
};