const deDE: { [name: string]: string } = {
    'STR_DELETE_PARK': 'Delete park',
    'STR_DELETE_SEQUENCE': 'Delete park sequence',
    'STR_DELETE_CONFIRM_TEXT': 'Are you sure you want to delete\n{STRING}?',
    'STR_TITLE_EDITOR_TITLE': 'Titelsequenzen',
    'STR_TITLE_SEQUENCE': 'Titelsequenz:',
    'STR_TITLE_EDITOR_ACTION_CREATE': 'Erstellen',
    'STR_TITLE_EDITOR_ACTION_CREATE_SEQUENCE_TIP': 'Eine neue Titelsequenz von{NEWLINE}Grund auf neu erstellen',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE': 'Duplizieren',
    'STR_TITLE_EDITOR_ACTION_DUPLICATE_SEQUENCE_TIP': 'Neue Titelsequenz durch duplizieren der aktuellen Titelsequenz erstellen',
    'STR_TITLE_EDITOR_ACTION_DELETE': 'Entfernen',
    'STR_TITLE_EDITOR_ACTION_DELETE_SEQUENCE_TIP': 'Aktuelle Titelsequenz löschen',
    'STR_TITLE_EDITOR_ACTION_RENAME': 'Umbenennen',
    'STR_TITLE_EDITOR_ACTION_RENAME_SEQUENCE_TIP': 'Aktuelle Titelsequenz umbenennen',
    'STR_TITLE_EDITOR_ACTION_ADD': 'Hinzufügen',
    'STR_TITLE_EDITOR_ACTION_ADD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_REMOVE': 'Entfernen',
    'STR_TITLE_EDITOR_ACTION_REMOVE_TIP': '',
    'STR_TITLE_EDITOR_ACTION_RENAME_TIP': '',
    'STR_TITLE_EDITOR_ACTION_LOAD': 'Laden',
    'STR_TITLE_EDITOR_ACTION_LOAD_TIP': '',
    'STR_TITLE_EDITOR_ACTION_INSERT': 'Einfügen',
    'STR_TITLE_EDITOR_ACTION_EDIT': 'Bearbeiten',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO': 'Springen zu',
    'STR_TITLE_EDITOR_ACTION_INSERT_TIP': 'Neuen Befehl einfügen',
    'STR_TITLE_EDITOR_ACTION_EDIT_TIP': 'Ausgewählten Befehl bearbeiten',
    'STR_TITLE_EDITOR_ACTION_DELETE_TIP': 'Ausgewählten Befehl löschen',
    'STR_TITLE_EDITOR_ACTION_SKIP_TO_TIP': 'Zum ausgewählten Befehl in{NEWLINE}der Titelsequenz springen',
    'STR_TITLE_EDITOR_ACTION_MOVE_DOWN_TIP': 'Ausgewählten Befehl nach oben verschieben',
    'STR_TITLE_EDITOR_ACTION_MOVE_UP_TIP': 'Ausgewählten Befehl nach unten verschieben',
    'STR_TITLE_EDITOR_ACTION_RESTART_TIP': 'Titelsequenz neu starten',
    'STR_TITLE_EDITOR_ACTION_STOP_TIP': 'Titelsequenz stoppen',
    'STR_TITLE_EDITOR_ACTION_PLAY_TIP': 'Titelsequenz abspielen',
    'STR_TITLE_EDITOR_ACTION_SKIP_TIP': 'Zum nächsten „Warten“-Befehl springen',
    'STR_YES': 'Ja',
    'STR_OK': 'OK',
    'STR_CANCEL': 'Abbrechen',
    'STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE': 'Objekt auswählen',
    'STR_TITLE_COMMAND_EDITOR_COMMAND_LABEL': 'Befehl:',
    'STR_TITLE_COMMAND_EDITOR_TITLE': 'Befehlseditor',
    'STR_TITLE_EDITOR_ACTION_LOAD_SAVE': 'Spielstand laden',
    'STR_TITLE_EDITOR_ARGUMENT_SAVEFILE': 'Zu ladender Spielstand:',
    'STR_TITLE_EDITOR_ACTION_LOAD_SCENARIO': 'Szenario laden',
    'STR_TITLE_EDITOR_ARGUMENT_SCENARIO': 'Szenario laden:',
    'STR_TITLE_EDITOR_COMMAND_TYPE_LOCATION': 'Position',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ROTATE': 'Drehen',
    'STR_TITLE_EDITOR_COMMAND_TYPE_ZOOM': 'Zoom',
    'STR_TITLE_EDITOR_COMMAND_TYPE_SPEED': 'Geschwindigkeit',
    'STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW': 'Objekt folgen ',
    'STR_TITLE_EDITOR_COMMAND_TYPE_WAIT': 'Warten',
    'STR_TITLE_EDITOR_ARGUMENT_COORDINATES': 'Koordinaten:',
    'STR_TITLE_EDITOR_ARGUMENT_ROTATIONS': 'Drehungen gegen Uhrzeigersinn:',
    'STR_TITLE_EDITOR_ARGUMENT_ZOOM_LEVEL': 'Zoomstufe:',
    'STR_TITLE_EDITOR_ARGUMENT_SPEED': 'Geschwindigkeit:',
    'STR_TITLE_EDITOR_ARGUMENT_WAIT_SECONDS': 'Zu wartende Millisekunden:',
    'STR_TITLE_EDITOR_RESTART': 'Neustart',
    'STR_TITLE_EDITOR_END': 'Ende',
    'STR_TITLE_COMMAND_EDITOR_ACTION_GET_LOCATION': 'Erhalten',
    'STR_TITLE_COMMAND_EDITOR_ACTION_SELECT_SCENARIO': 'Select',
    'STR_SPEED_NORMAL': 'Normale Geschwindigkeit',
    'STR_SPEED_QUICK': 'Erhöhte Geschwindigkeit',
    'STR_SPEED_FAST': 'Hohe Geschwindigkeit',
    'STR_SPEED_TURBO': 'Sehr hohe Geschwindigkeit',
    'STR_SPEED_HYPER': 'Extreme Geschwindigkeit',
    'STR_TITLE_COMMAND_EDITOR_NO_SAVE_SELECTED': 'Kein Spielstand ausgewählt',
    'STR_TITLE_COMMAND_EDITOR_NO_SCENARIO_SELECTED': 'Kein Szenario ausgewählt',
    'STR_TITLE_EDITOR_ENTER_NAME_FOR_SEQUENCE': 'Namen für Titelsequenz eingeben:',
};